### PR TITLE
Support secure domoticz server

### PR DESCRIPTION
**Pull request by coralrosoff**
Add domoticz server authentication and some more styling

### CODE REVIEW

**Comment by coralrosoff** [comment]
What do you thing about remove the plain text username and password?
It's not good idea to use then at all, even in the domoticz website.
We can leave only the encoded option

**Comment by DaanJJansen** [comment]
Nice, looks good

**Comment by coralrosoff** [comment]
Thanks.
What do you think about the idea to remove the plain text password field?

**Comment by DaanJJansen** [comment]
i would indeed use either one, or go for the encoded, or the plain... What is best practice at other plugins?

I honestly don't use username/password on domoticz side, so eitherway is fine by me :-)

**Comment by coralrosoff** [comment]
In the API documentation they recommend only to use the encoded one so I think it's better to leave it encoded all the way..
I will make one more pull request for that

**Pull request merged**
